# Generated by Django 4.2.3 on 2023-07-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'My super user', 'verbose_name_plural': 'My super users'},
        ),
    ]
